version: '3.8'

services:
  backend:
    image: 156041431760.dkr.ecr.eu-west-2.amazonaws.com/youlend/loan-api:latest
    container_name: loan-api
    ports:
      - "8080:5000"
    networks:
      - loan-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000

  frontend:
    image: 156041431760.dkr.ecr.eu-west-2.amazonaws.com/youlend/loan-website:latest
    container_name: loan-website
    ports:
      - "8081:4200"
    depends_on:
      - backend
    networks:
      - loan-network

networks:
  loan-network:
    driver: bridge
